import Footer from './coponent/footer/Footer';
import Navbar from './coponent/navbar/Navbar';
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DigiCruiter',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[#F5F5F5]">
          <Navbar></Navbar>
        </div>
        <main className="bg-[#F5F5F5]">{children}</main>
        <div className="bg-[#F5F5F5]">
          <Footer></Footer>
        </div>
        
      </body>
    </html>
  );
}
